// <auto-generated />
using System;
using HRMapp.Data.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRMapp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250612084250_fixNullCutiLog")]
    partial class fixNullCutiLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HRMapp.Data.Model.City", b =>
                {
                    b.Property<int>("city_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("city_id"));

                    b.Property<string>("city_name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("province_id")
                        .HasColumnType("int");

                    b.HasKey("city_id");

                    b.HasIndex("province_id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("HRMapp.Data.Model.Contract", b =>
                {
                    b.Property<int>("contract_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("contract_id"));

                    b.Property<string>("author")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("contract_date")
                        .HasColumnType("date");

                    b.Property<int>("contract_duration")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("employee_id")
                        .HasColumnType("int");

                    b.Property<DateOnly>("end_date")
                        .HasColumnType("date");

                    b.Property<int>("gaji_pokok")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("contract_id");

                    b.HasIndex("employee_id");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("HRMapp.Data.Model.Course", b =>
                {
                    b.Property<int>("course_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("course_id"));

                    b.Property<DateOnly>("course_graduation_date")
                        .HasColumnType("date");

                    b.Property<string>("course_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("employee_id")
                        .HasColumnType("int");

                    b.HasKey("course_id");

                    b.HasIndex("employee_id");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("HRMapp.Data.Model.Cuti", b =>
                {
                    b.Property<int>("cuti_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("created_by")
                        .HasColumnType("longtext");

                    b.Property<int>("cuti_day_count")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("cuti_end_date")
                        .HasColumnType("date");

                    b.Property<DateOnly>("cuti_start_date")
                        .HasColumnType("date");

                    b.Property<int>("employee_id")
                        .HasColumnType("int");

                    b.Property<string>("reason")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("updated_by")
                        .HasColumnType("longtext");

                    b.HasKey("cuti_id");

                    b.ToTable("Cuti");
                });

            modelBuilder.Entity("HRMapp.Data.Model.Department", b =>
                {
                    b.Property<int>("department_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("department_id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("department_id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("HRMapp.Data.Model.Education", b =>
                {
                    b.Property<int>("education_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("education_id"));

                    b.Property<string>("education_type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("major")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("education_id");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("HRMapp.Data.Model.Employee", b =>
                {
                    b.Property<int>("employee_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("employee_id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("birthdate")
                        .HasColumnType("date");

                    b.Property<string>("birthplace")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("city_id")
                        .HasColumnType("int");

                    b.Property<int>("department_id")
                        .HasColumnType("int");

                    b.Property<int>("education_id")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("employee_status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("factory_id")
                        .HasColumnType("int");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly?>("graduation_date")
                        .HasColumnType("date");

                    b.Property<DateOnly>("hire_date")
                        .HasColumnType("date");

                    b.Property<int>("job_id")
                        .HasColumnType("int");

                    b.Property<string>("marital_status")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("nik")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("nip")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("pic_path")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("religion_id")
                        .HasColumnType("int");

                    b.Property<string>("skill")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("yearly_cuti_left")
                        .HasColumnType("int");

                    b.HasKey("employee_id");

                    b.HasIndex("city_id");

                    b.HasIndex("department_id");

                    b.HasIndex("education_id");

                    b.HasIndex("factory_id");

                    b.HasIndex("job_id");

                    b.HasIndex("religion_id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HRMapp.Data.Model.Factory", b =>
                {
                    b.Property<int>("factory_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("factory_id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("personnel_capacity")
                        .HasColumnType("int");

                    b.HasKey("factory_id");

                    b.ToTable("Factories");
                });

            modelBuilder.Entity("HRMapp.Data.Model.Job", b =>
                {
                    b.Property<int>("job_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("job_id"));

                    b.Property<string>("job_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("job_id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("HRMapp.Data.Model.LogEmployee", b =>
                {
                    b.Property<int>("log_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("log_id"));

                    b.Property<DateTime>("deleted_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("employee_id")
                        .HasColumnType("int");

                    b.Property<string>("field_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("new_value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("old_value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("updated_by")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("log_id");

                    b.HasIndex("employee_id");

                    b.ToTable("LogEmployees");
                });

            modelBuilder.Entity("HRMapp.Data.Model.Province", b =>
                {
                    b.Property<int>("province_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("province_id"));

                    b.Property<string>("province_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("province_id");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("HRMapp.Data.Model.Religion", b =>
                {
                    b.Property<int>("religion_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("religion_id"));

                    b.Property<string>("religion_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("religion_id");

                    b.ToTable("Religions");
                });

            modelBuilder.Entity("HRMapp.Data.Model.Session", b =>
                {
                    b.Property<int>("session_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("session_id"));

                    b.Property<DateTime>("last_login")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.Property<string>("user_token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("session_id");

                    b.HasIndex("user_id");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("HRMapp.Data.Model.Tunjangan", b =>
                {
                    b.Property<int>("tunjangan_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("tunjangan_id"));

                    b.Property<int?>("amount")
                        .HasColumnType("int");

                    b.Property<int>("contract_id")
                        .HasColumnType("int");

                    b.Property<string>("tunjangan_name")
                        .HasColumnType("longtext");

                    b.HasKey("tunjangan_id");

                    b.HasIndex("contract_id");

                    b.ToTable("Tunjangan");
                });

            modelBuilder.Entity("HRMapp.Data.Model.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("user_id"));

                    b.Property<string>("authority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("forgot_pass_token")
                        .HasColumnType("longtext");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("user_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HRMapp.Data.Model.City", b =>
                {
                    b.HasOne("HRMapp.Data.Model.Province", "Provinces")
                        .WithMany()
                        .HasForeignKey("province_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provinces");
                });

            modelBuilder.Entity("HRMapp.Data.Model.Contract", b =>
                {
                    b.HasOne("HRMapp.Data.Model.Employee", "Employee")
                        .WithMany("Contracts")
                        .HasForeignKey("employee_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRMapp.Data.Model.Course", b =>
                {
                    b.HasOne("HRMapp.Data.Model.Employee", "Employee")
                        .WithMany("Courses")
                        .HasForeignKey("employee_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRMapp.Data.Model.Cuti", b =>
                {
                    b.HasOne("HRMapp.Data.Model.Employee", "Employee")
                        .WithMany("Cuti")
                        .HasForeignKey("cuti_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRMapp.Data.Model.Employee", b =>
                {
                    b.HasOne("HRMapp.Data.Model.City", "City")
                        .WithMany()
                        .HasForeignKey("city_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMapp.Data.Model.Department", "Department")
                        .WithMany()
                        .HasForeignKey("department_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMapp.Data.Model.Education", "Education")
                        .WithMany()
                        .HasForeignKey("education_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMapp.Data.Model.Factory", "Factory")
                        .WithMany()
                        .HasForeignKey("factory_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMapp.Data.Model.Job", "Job")
                        .WithMany()
                        .HasForeignKey("job_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMapp.Data.Model.Religion", "Religion")
                        .WithMany()
                        .HasForeignKey("religion_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Department");

                    b.Navigation("Education");

                    b.Navigation("Factory");

                    b.Navigation("Job");

                    b.Navigation("Religion");
                });

            modelBuilder.Entity("HRMapp.Data.Model.LogEmployee", b =>
                {
                    b.HasOne("HRMapp.Data.Model.Employee", "Employee")
                        .WithMany("LogEmployees")
                        .HasForeignKey("employee_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRMapp.Data.Model.Session", b =>
                {
                    b.HasOne("HRMapp.Data.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRMapp.Data.Model.Tunjangan", b =>
                {
                    b.HasOne("HRMapp.Data.Model.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("contract_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("HRMapp.Data.Model.Employee", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Courses");

                    b.Navigation("Cuti");

                    b.Navigation("LogEmployees");
                });
#pragma warning restore 612, 618
        }
    }
}
